apiVersion: v1
kind: Pod
metadata:
  name: password-gen-env-demo
  labels:
    env: demo
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: password-gen-env
      image: localhost:32000/password-gen-env:v1.0.0
      volumeMounts:
        - mountPath: "/logs"
          name: pv-storage
      env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: password-policy
              key: demo.name
        - name: PASSWORD_COUNT
          valueFrom:
            configMapKeyRef:
              name: password-policy
              key: demo.password.count
        - name: PASSWORD_MINIMUM_LENGTH
          valueFrom:
            configMapKeyRef:
              name: password-policy
              key: demo.password.minimumLength
        - name: PASSWORD_MAXIMUM_LENGTH
          valueFrom:
            configMapKeyRef:
              name: password-policy
              key: demo.password.maximumLength
